config/routes.rb
Rails.application.routes.draw do
  root to: "static_pages#home"
  devise_for :users

  namespace :admin do
    resources :users
    resources :films
    resources :categories
    resources :films
    resources :scripts
  end

  resources :scripts
  resources :static_pages
  resources :users
  resources :likes
  resources :relationships
end

app/models/script.rb
class Script < ApplicationRecord
  include ActionActivity
  after_create :create_script_activity
  validates :title, :content, presence: true, length: {minimum: 2}

  belongs_to :user

  scope :load_script_by_user, ->user {where user_id: user.id}

  enum status: [:request, :approve, :reject]

  private

  def create_script_activity
    create_activity user_id, id, Activity.action_types[:submit_script],
      I18n.t("activity.submit_script")
  end
end

app/controllers/admin/scripts_controller.rb
class Admin::ScriptsController < ApplicationController
  include ResponseMessage
  before_action :checking_logged_user
  before_action :checking_admin, only: [:index, :edit, :update, :destroy]
  before_action :load_script, only: [:show, :edit, :update, :destroy]

  def index
    @search = Script.ransack params[:q]
    @scripts = @search.result.paginate page: params[:page],
      per_page: Settings.paging
  end

  def show
  end

  def edit
  end

  def update
    if @script.update script_params
      response_to_message t("activity.message_approve"), admin_scripts_url
    else
      response_to_message t("script_film.message_fail"), admin_scripts_url
    end
  end

  private

  def script_params
    params.require(:script).permit :status
  end

  def load_script
    begin
      @script = Script.find params[:id]
    rescue Exception
      response_to_message t("script_film.not_found"), admin_scripts_url
    end
  end
end

app/controllers/scripts_controller.rb
class ScriptsController < ApplicationController
  include ResponseMessage
  before_action :load_script, only: [:show, :edit, :update, :destroy]

  def index
    @search = current_user.scripts.ransack params[:q]
    @scripts = @search.result.paginate page: params[:page],
      per_page: Settings.paging
  end

  def show
  end

  def edit
  end

  def update
    if @script.update script_params
      response_to_message t("script_film.message_apdate_sucess"), scripts_url
    else
      response_to_message t("script_film.message_apdate_notsucess"), scripts_url
    end
  end

  def new
    @script = current_user.scripts.build
  end

  def create
    @script = current_user.scripts.build script_params
    if @script.save
      response_to_message t("script_film.create_sucess"), scripts_url
    else
      response_message_errors @script
    end
  end

  def destroy
    if @script.destroy
      response_to_message t("script_film.deleted"), scripts_url
    else
      response_to_message t("script_film.not_deleted"), scripts_url
    end
  end

  private

  def script_params
    params.require(:script).permit :title, :content
  end

  def load_script
    begin
      @script = Script.find params[:id]
    rescue Exception
      response_to_message t("script_film.not_found"), scripts_url
    end
  end
end

app/views/scripts/_form.html.erb
<div class="bs-example" data-example-id="form-validation-states">
  <%= form_for @script do |f| %>
    <%= render "/share/error_message", object: f.object %>

    <div class="form-group has-success">
      <%= f.label :title, class:"control-label" %><br />
      <%= f.text_field :title, autofocus: true, class:"form-control",
        placeholder:t("script_film.title") %>
    </div>

    <div class="form-group has-success">
      <%= f.label :content, class:"control-label" %><br />
      <%= f.text_area :content, autofocus: true, rows: Settings.size_row_area,
        class:"form-control", placeholder:t("script_film.content") %>
    </div>

    <div class="col-md-offset-5">
      <%= f.submit t("authenticate.submid"), class:"btn btn-success" %>
    </div>
  <% end %>
</div>

app/views/scripts/_script.html.erb
<tbody>
  <tr>
    <td><span class="glyphicon glyphicon-folder-open"></span></td>
    <td><%= link_to script.title, script_path(script.id) %></td>
    <td><%= script.content %></td>
    <td>
      <% if script.request? %>
        <span class="glyphicon glyphicon-flag"></span>
      <% end %>
      <% if script.approve? %>
        <span class="glyphicon glyphicon-ok-circle"></span>
      <% end %>
      <% if script.reject? %>
        <span class="glyphicon glyphicon-remove-circle"></span>
      <% end %>
    </td>
    <td><%= script.created_at %></td>
  </tr>
</tbody>

app/views/scripts/edit.html.erb
<% provide :title, t("static_pages.title_script") %>
<%= render "form", script: @script %>
<%= link_to t("authenticate.back"), scripts_path %>

app/views/scripts/index.html.erb
<% provide :title, t("static_pages.title_script") %>
<div class="container-fluid">
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-2">
    <div class="field">
      <div class="form-group">
        <%= link_to t("script_film.new_script"), new_script_path,
          class:"right-post glyphicon glyphicon-edit" %>
      </div>
    </div>
  </div>
</div>

<div class="panel panel-info">
  <div class="panel-heading">
    <h3 class="panel-title"><%= t "manage_user.list_film" %></h3>
  </div>
  <div class="panel-body">
    <table class="table table-bordered table-striped table-hover">
      <thead>
        <tr>
          <%= search_form_for @search do |f| %>
            <th></th>
            <th class="center"><%= f.search_field :title_cont, autofocus: true %></th>
            <th class="center"><%= f.search_field :content_cont, autofocus: true %></th>
            <th colspan="2" class="center"><%= f.submit t("action.search"),
              class:"btn btn-success" %></th>
          <% end %>
        </tr>
        <tr>
          <th></th>
          <th><%= sort_link @search, :title, t("script_film.title") %></th>
          <th><%= sort_link @search, :content, t("script_film.content") %></th>
          <th><%= t "script_film.status" %></th>
          <th><%= sort_link @search, :created_at, t("script_film.create_date") %></th>
        </tr>
      </thead>
      <%= render partial: "script", collection: @scripts %>
    </table>
  </div>
  <%= will_paginate @scripts %>
</div>
<br>

app/views/scripts/new.html.erb
<% provide :title, t("static_pages.title_script") %>
<%= render "form", script: @script %>
<%= link_to t("authenticate.back"), scripts_path %>

app/views/scripts/show.html.erb
<% provide :title, t("static_pages.title_script") %>
<div class="panel panel-info">
  <div class="panel-heading">
    <h3 class="panel-title"><%= t "manage_user.title" %> : <%= @script.title %></h3>
  </div>
  <div class="panel-body">
    <div class="panel-body">
      <%= @script.content %>
    </div>
    <div class="footer">
      <%= link_to t("authenticate.back"), :back %>
      <%= link_to t("action.edit"), edit_script_path(@script.id),
        class:"glyphicon glyphicon-pencil action-post-right" %>
      <%= link_to "", script_path, class:"glyphicon glyphicon-trash", method: :delete,
        data: {confirm: t("manage_user.you_sure")} %>
    </div>
  </div>
</div>