config/routes.rb
Rails.application.routes.draw do
  root to: "static_pages#home"
  devise_for :users

  namespace :admin do
    resources :users
    resources :films
    resources :categories
    resources :films
    resources :scripts
  end

  resources :scripts
  resources :static_pages
  resources :users
  resources :likes
  resources :relationships
end

app/models/film.rb
class Film < ApplicationRecord
  validates :name_film, :picture_film, :link_trailer,  presence: true, length:
    {minimum: 2, maximum: 200}
  validates :rating_film, numericality: {only_integer: true}
  validates :count_like, numericality: {only_integer: true}

  belongs_to :category

  has_many :passive_likes, class_name: Like.name,
    foreign_key: :like_film_id, dependent: :destroy
  has_many :liked, through: :passive_likes, source: :like_user

  ARRAY_RATE = [[I18n.t("manage_films.rate_none"), nil],
    [I18n.t("manage_films.rate_1"), I18n.t("manage_films.rate_1")],
    [I18n.t("manage_films.rate_2"), I18n.t("manage_films.rate_2")],
    [I18n.t("manage_films.rate_3"), I18n.t("manage_films.rate_3")],
    [I18n.t("manage_films.rate_4"), I18n.t("manage_films.rate_4")],
    [I18n.t("manage_films.rate_5"), I18n.t("manage_films.rate_5")]]

  class << self
    def to_csv
      CSV.generate do |csv|
        csv << column_names
        all.find_each do |film|
          csv << film.attributes.values_at(*column_names)
        end
      end
    end
  end

  def calculate_rating_film count_like
    rate = count_like / Settings.div_rate
    rate >= Settings.max_rate ? Settings.max_rate : rate
  end
end

app/controllers/admin/films_controller.rb
class Admin::FilmsController < ApplicationController
  include ResponseMessage, ExportCsv
  before_action :checking_logged_user
  before_action :checking_admin, only: [:index, :edit, :update, :destroy]
  before_action :load_film, only: [:show, :edit, :update, :destroy]

  def index
    @search = Film.ransack params[:q]
    @films = @search.result.paginate page: params[:page],
      per_page: Settings.paging
    respond_to_csv @films
  end

  def show
  end

  def edit
    @categories = Category.all
  end

  def update
    if @film.update film_params
      response_to_message t("manage_films.message_apdate_sucess"),
        admin_films_url
    else
      response_to_message t("manage_films.message_apdate_notsucess"),
        admin_films_url
    end
  end

  def new
    @film = Film.new
    @categories = Category.all
  end

  def create
    @film = Film.new film_params
    if @film.save
      response_to_message t("manage_films.create_sucess"), admin_films_url
    else
      response_message_errors @film
    end
  end

  def destroy
    if @film.destroy
      response_to_message t("manage_films.deleted"), admin_films_url
    else
      response_to_message t("manage_films.not_deleted"), admin_films_url
    end
  end

  private

  def film_params
    params.require(:film).permit :name_film, :year_screen, :picture_film,
      :link_trailer, :category_id
  end

  def load_film
    begin
      @film = Film.find params[:id]
    rescue Exception
      response_to_message t("manage_films.not_found"), admin_films_url
    end
  end
end

app/views/admin/films/_film.html.erb
<tbody>
  <tr>
    <td><img src="<%= film.picture_film %>" alt=""></td>
    <td><%= film.name_film %></td>
    <td><%= film.year_screen %></td>
    <td><%= film.rating_film %></td>
    <td><%= film.count_like %></td>
    <td><%= link_to t("action.show"), static_page_path(film.id),
      class:"glyphicon glyphicon-upload" %></td>
    <td><%= link_to t("action.edit"), edit_admin_film_path(film.id),
      class:"glyphicon glyphicon-pencil" %></td>
    <td><%= link_to t("action.destroy"), admin_film_path(film.id),
      class:"glyphicon glyphicon-remove",
      method: :delete, data: {confirm: t("manage_user.you_sure")} %></td>
  </tr>
</tbody>

app/views/admin/films/_form.html.erb
<div class="bs-example" data-example-id="form-validation-states">
  <%= form_for [:admin, @film] do |f| %>
    <%= render "/share/error_message", object: f.object %>

    <div class="form-group has-success">
      <%= f.label :name_film , class:"control-label" %><br />
      <%= f.text_field :name_film, autofocus: true, class:"form-control" %>
    </div>

    <div class="form-group has-success">
      <%= f.label :year_screen, class:"control-label" %><br />
      <%= f.date_field :year_screen, autofocus: true, class:"form-control" %>
    </div>

    <div class="form-group has-success">
      <%= f.label :category_id, class:"control-label" %><br />
      <%= f.select :category_id, options_for_select(@categories.collect{ |category|
        [category.name, category.id]}, params[:category_id]), {}, {class:"form-control"} %>
    </div>

    <div class="form-group has-success">
      <%= f.label :picture_film, class:"control-label" %><br />
      <%= f.text_field :picture_film, autofocus: true, class:"form-control" %>
    </div>

    <div class="form-group has-success">
      <%= f.label :link_trailer, class:"control-label" %><br />
      <%= f.text_field :link_trailer, autofocus: true, class:"form-control" %>
    </div>

    <div class="col-md-offset-5">
      <%= f.submit t("authenticate.submid"), class:"btn btn-success" %>
    </div>
  <% end %>
</div>

app/views/admin/films/edit.html.erb
<% provide :title, t("static_pages.title_edit_film") %>
<%= render "form", film: @film %>
<%= link_to t("authenticate.back"), admin_films_path %>

app/views/admin/films/index.html.erb
<% provide :title, t("manage_films.list_film") %>
<div class="panel panel-info">
  <div class="panel-heading">
    <h3 class="panel-title"><%= t "manage_user.list_film" %></h3>
  </div>
  <div class="panel-body">
    <table class="table table-bordered table-striped table-hover">
      <thead>
        <tr>
          <%= search_form_for @search, url: admin_films_path do |f| %>
            <th></th>
            <th class="center"><%= f.search_field :name_film_cont, size: 10 %></th>
            <th class="center"><%= f.search_field :year_screen_cont, size: 10 %></th>
            <th class="center"><%= f.search_field :rating_film_cont, size: 10 %></th>
            <th class="center"><%= f.search_field :count_like_cont, size: 10 %></th>
            <th colspan="3" class="center"><%= f.submit t("action.search"),
              class:"btn btn-success" %></th>
          <% end %>
        </tr>
        <tr>
          <th></th>
          <th><%= sort_link @search, :name_film, t("manage_films.name_film") %></th>
          <th><%= sort_link @search, :year_screen, t("manage_films.year_screen") %></th>
          <th><%= sort_link @search, :rating_film,  t("manage_films.raiting") %></th>
          <th><%= sort_link @search, :count_like, t("manage_films.count_like") %></th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <%= render partial: "film", collection: @films %>
    </table>
  </div>
  <%= will_paginate @films %>
</div>
<%= link_to t("manage_films.new_film"), new_admin_film_path %>
<%= link_to t("manage_films.export_csv"), Settings.url_export_film, class:"right-post" %>
<br>

app/views/admin/films/new.html.erb
<% provide :title, t("static_pages.title_new_film") %>
<%= render "form", film: @film %>
<%= link_to t("authenticate.back"), admin_films_path %>