config/routes.rb
Rails.application.routes.draw do
  root to: "static_pages#home"
  devise_for :users

  namespace :admin do
    resources :users
    resources :films
    resources :categories
    resources :films
    resources :scripts
  end

  resources :scripts
  resources :static_pages
  resources :users
  resources :likes
  resources :relationships
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable
  before_save :downcase_email
  validates :fullname, presence: true, length: {maximum: 50}
  validates :address, presence: true, length: {maximum: 200}
  validates :phone, length: {maximum: 11}

  ARRAY_ROLE = [[I18n.t("role.none"), nil], [I18n.t("role.role_user"),
    I18n.t("role.role_user")], [I18n.t("role.role_admin"), I18n.t("role.role_admin")]]

  has_many :scripts, dependent: :destroy
  has_many :activities

  has_many :active_relationships, class_name: Relationship.name,
    foreign_key: :follower_id, dependent: :destroy
  has_many :passive_relationships, class_name: Relationship.name,
    foreign_key: :followed_id, dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  has_many :active_likes, class_name: Like.name,
    foreign_key: :like_user_id, dependent: :destroy
  has_many :liking, through: :active_likes, source: :like_film

  def is_admin?
    role == Settings.role.role_admin
  end

  def follow other_user
    following << other_user
  end

  def unfollow other_user
    following.destroy other_user
  end

  def following? other_user
    following.include? other_user
  end

  def like film
    liking << film
  end

  def unlike film
    liking.destroy film
  end

  def liking? film
    liking.include? film
  end

  def is_user? user
    self == user
  end

  private

  def downcase_email
    self.email = email.downcase
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  include ResponseMessage
  before_action :checking_logged_user
  before_action :checking_admin, only: [:index, :edit, :update, :destroy]
  before_action :load_user, only: [:show, :edit, :update, :destroy]

  def index
    @search = User.ransack params[:q]
    @users = @search.result.paginate page: params[:page],
      per_page: Settings.paging
  end

  def show
  end

  def edit
  end

  def destroy
    if @user.destroy
      response_to_message t("manage_user.deleted"), admin_users_url
    else
      response_to_message t("manage_user.not_deleted"), admin_users_url
    end
  end

  def update
    if @user.update user_params
      response_to_message t("manage_user.admin_update_sucess"), admin_users_url
    else
      response_to_message t("manage_user.admin_update_not_sucess"), admin_users_url
    end
  end

  private

  def user_params
    params.require(:user).permit(:fullname, :birthday, :address, :phone,
      :email, :role)
  end

  def load_user
    begin
      @user = User.find(params[:id])
    rescue Exception
      response_to_message t("manage_user.not_found"), root_url
    end
  end
end

app/controllers/concerns/user_controller.rb
module UserController
  extend ActiveSupport::Concern

  included do
    def response_to_message message, url
      respond_to do |format|
        format.html {redirect_to url, notice: message}
        format.json {head :no_content}
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include ResponseMessage
  before_action :load_user, only: [:show, :edit, :update]

  def show
    if current_user.active_relationships.find_by(followed: @user.id).nil?
      @active_relationship = current_user.active_relationships.build
    else
      @active_relationship = current_user.active_relationships.find_by followed_id: @user.id
    end
    @activities = @user.activities.paginate page: params[:page],
      per_page: Settings.paging
  end

  def edit
  end

  def update
    if @user.update user_params
      response_to_message t("manage_user.admin_update_sucess"),
        user_url(@user.id)
    else
      response_to_message t("manage_user.admin_update_not_sucess"),
        user_url(@user.id)
    end
  end

  private

  def user_params
    params.require(:user).permit :fullname, :birthday, :address, :phone,
      :email, :role
  end

  def load_user
    begin
      @user = User.find params[:id]
    rescue Exception
      response_to_message t("manage_user.not_found"), root_url
    end
  end
end

app/views/admin/users/_user.html.erb
<tbody>
  <tr>
    <td><%= user.fullname %></td>
    <td><%= user.birthday %></td>
    <td><%= user.address %></td>
    <td><%= user.email %></td>
    <td><%= user.phone %></td>
    <td><%= user.role %></td>
    <td><%= link_to t("manage_user.show"), user_path(user.id),
      class:"glyphicon glyphicon-upload" %></td>
    <td><%= link_to t("manage_user.edit"), edit_admin_user_path(user.id),
      class:"glyphicon glyphicon-pencil" %></td>
    <td><%= link_to t("manage_user.destroy"), admin_user_path(user.id),
      class:"glyphicon glyphicon-remove", method: :delete,
      data: {confirm: t("manage_user.you_sure")} %></td>
  </tr>
</tbody>

app/views/admin/users/edit.html.erb
<% provide :title, t("authenticate.edituser") %>
<%= form_for [:admin, @user] do |f| %>
  <div class="form-group has-success">
    <%= f.label :fullname , class:"control-label" %><br />
    <%= f.text_field :fullname, autofocus: true, class:"form-control" %>
  </div>

  <div class="form-group has-success">
    <%= f.label :birthday, class:"control-label" %><br />
    <%= f.date_field :birthday, autofocus: true, class:"form-control" %>
  </div>

  <div class="form-group has-success">
    <%= f.label :address, class:"control-label" %><br />
    <%= f.text_field :address, autofocus: true, class:"form-control" %>
  </div>

  <div class="form-group has-success">
    <%= f.label :phone, class:"control-label" %><br />
    <%= f.text_field :phone, autofocus: true, class:"form-control" %>
  </div>

  <div class="form-group has-success">
    <%= f.label :email, class:"control-label" %><br />
    <%= f.email_field :email, autofocus: true, class:"form-control" %>
  </div>

  <div class="form-group has-success">
    <%= f.label :role, class:"control-label" %><br />
    <%= f.select :role, options_for_select(User::ARRAY_ROLE, f.object.role), {},
      {class:"form-control"} %>
  </div>

  <div class="col-md-offset-5">
    <%= f.submit t("authenticate.update"), class:"btn btn-success" %>
  </div>
<% end %>
<%= link_to t("authenticate.back"), :back %>

app/views/admin/users/index.html.erb
<% provide :title, t("static_pages.lst_user") %>
<div class="panel panel-info">
  <div class="panel-heading">
    <h3 class="panel-title"><%= t "manage_user.list_user" %></h3>
  </div>
  <div class="panel-body">
    <table class="table table-bordered table-striped table-hover">
      <thead>
        <tr>
          <%= search_form_for @search, url: admin_users_path do |f| %>
            <th class="center"><%= f.search_field :fullname_cont, size: 10 %></th>
            <th class="center"><%= f.search_field :birthday_cont, size: 10 %></th>
            <th class="center"><%= f.search_field :address_cont, size: 10 %></th>
            <th class="center"><%= f.search_field :email_cont, size: 10 %></th>
            <th class="center"><%= f.search_field :phone_cont, size: 10 %></th>
            <th class="center"><%= f.search_field :role_cont, size: 10 %></th>
            <th colspan="3" class="center"><%= f.submit t("action.search"),
              class:"btn btn-success" %></th>
          <% end %>
        </tr>
        <tr>
          <th><%= t "manage_user.name" %></th>
          <th><%= t "manage_user.birthday" %></th>
          <th><%= t "manage_user.address" %></th>
          <th><%= t "manage_user.email" %></th>
          <th><%= t "manage_user.phone" %></th>
          <th><%= t "manage_user.role" %></th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <%= render partial: "user", collection: @users %>
    </table>
  </div>
  <%= will_paginate @users %>
</div>
<br>