config/routes.rb
Rails.application.routes.draw do
  root to: "static_pages#home"
  devise_for :users

  namespace :admin do
    resources :users
    resources :films
    resources :categories
    resources :films
    resources :scripts
  end

  resources :scripts
  resources :static_pages
  resources :users
  resources :likes
  resources :relationships
end

app/views/layouts/_footer.html.erb
<div class="page-header"></div>
<div class="col-md-offset-5">
  <span class="glyphicon glyphicon-facetime-video"> <%= t "static_pages.footer_vfs" %></span>
  <span class="glyphicon glyphicon-bullhorn"></span>
  <span class="glyphicon glyphicon-bullhorn"></span>
</div>

app/views/layouts/_header.html.erb
<div class="header clearfix margin-container">
  <nav>
    <ul class="nav nav-pills pull-right">
      <li role="presentation"><%= link_to t("static_pages.home"), root_path %></a></li>
      <li role="presentation"><a href="#"><%= t "static_pages.about" %></a></li>
      <li role="presentation"><a href="#"><%= t "static_pages.contact" %></a></li>
      <% if current_user.present? && !current_user.is_admin? %>
        <li><%= link_to t("static_pages.mypages"), scripts_path %></li>
      <% end %>
      <!-- Them dropdown menu-->
      <li role="presentation" class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button"
          aria-haspopup="true" aria-expanded="false">
          <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
          <% if current_user.present? %>
            <%= current_user.fullname %>
          <% elsif %>
          <%= t "static_pages.user" %>
          <% end %>
          <span class="caret"></span>
        </a>
        <ul class="dropdown-menu">
          <% if current_user.present? %>
            <li><%= link_to t("static_pages.profile"), user_path(current_user.id) %></li>
          <% end %>
          <% if current_user.present? && current_user.is_admin? %>
            <li><%= link_to t("static_pages.admin_film"), admin_films_path %></li>
            <li><%= link_to t("static_pages.admin_user"), admin_users_path %></li>
            <li><%= link_to t("static_pages.admin_category"), admin_categories_path %></li>
            <li><%= link_to t("static_pages.admin_script"), admin_scripts_path %></li>
          <% end %>
          <li><%= link_to t("static_pages.login"), new_user_session_path %></li>
          <li><%= link_to t("static_pages.register"), new_user_registration_path %></li>
          <li><%= link_to t("static_pages.logout"), destroy_user_session_path,
            method: :delete %></a></li>
        </ul>
      </li>
    </ul>
  </nav>
  <h3 class="text-muted"><a><span class="glyphicon glyphicon-knight"
    aria-hidden="true"></span> <%= t "static_pages.project_name" %></a></h3>
</div>
<hr>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= make_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track": "reload" %>
  </head>
  <body class="container">
    <%= render "layouts/header" %>

    <p class="notice text-success"><%= notice %></p>
    <p class="alert text-success"><%= alert %></p>

    <%= yield %>
    <%= render "layouts/footer" %>
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
  </body>
</html>